default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_dev
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: rolldx_development

test:
  <<: *default
  database: rolldx_test

production:
  <<: *default
  database: rolldx_production

